version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 700M

  db:
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "${NEXT_PUBLIC_SUPABASE_URL}"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
      DIRECT_URL: "${DIRECT_URL}"
      DATABASE_URL: "${DATABASE_URL}"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 700M